apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - european-transport-feeds
  - vbb-departure-hotline
  - fpti-js-badges
  - fptf-badges
  - db-rest
  - api-direkt-bahn-guru
  - bus-bahn-guru
  - example-app
